CC = gcc
CFLAGS = -std=gnu99 -pipe -O2 -Wall
LDFLAGS = -pipe -Wall
LDLIBS = -lfftw3 -lm

SOURCES = mmap.c common.c
OBJECTS = $(SOURCES:.c=.o)
EXEC = acq_c

all: $(SOURCES) $(EXEC)

$(EXEC): $(OBJECTS)
    $(CC) -o $@ $(LDFLAGS) $(OBJECTS)

.c.o:
    $(CC) -o $@ $(CFLAGS) -c $<

clean:
    rm *.o $(EXEC)
all:
	rm -f prtd
	gcc -std=gnu99 -o prtd prtd.c -lfftw3 -lm

